info:
  version: 1.0.1
  description: CHF initial local configuration

configuration:
  chfName: CHF # the name of this CHF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.113 # IP used to register to NRF
    bindingIPv4: 127.0.0.113  # IP used to bind the service
    port: 8000              # port used to bind the service
    tls: # the local path of TLS key
      pem: config/TLS/chf.pem # CHF TLS Certificate
      key: config/TLS/chf.key # CHF TLS Private key
  nrfUri: http://127.0.0.10:8000  # a valid URI of NRF
  serviceList:   # the SBI services provided by this CHF, refer to TS 32.291
    - serviceName: nchf-convergedcharging # Nchf_AMPolicyControl service
  mongodb:       # the mongodb connected by this CHF
    name: free5gc                  # name of the mongodb
    url: mongodb://localhost:27017 # a valid URL of the mongodb
  quotaValidityTime: 10000
  volumeLimit: 50000
  volumeLimitPDU: 10000
  volumeThresholdRate: 0.8
  cgf:
    hostIPv4: 127.0.0.1
    port: 2122
    listenPort: 2121
    tls:
      pem: config/TLS/chf.pem
      key: config/TLS/chf.key
  abmfDiameter:
    protocol: tcp 
    hostIPv4: 127.0.0.113
    port: 3868
    tls:
      pem: config/TLS/chf.pem
      key: config/TLS/chf.key
  rfDiameter: 
    protocol: tcp
    hostIPv4: 127.0.0.113
    port: 3869
    tls:
      pem: config/TLS/chf.pem # CHF TLS Certificate
      key: config/TLS/chf.key # CHF TLS Private key
    # the kind of log output
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  CHF:
    debugLevel: trace
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
